defaults:
  - _self_
  - params: default_params
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
read:
  preprocessed_trajectories: True
  piecewise_potential: True
  simulated_trajectories: True
  grid:
    from_file: False
    filename: single_paths.npz
save:
  preprocessed_trajectories: True
  piecewise_potential: True
  simulated_trajectories: True
plot:
  preprocessed_trajectories: True
  simulated_trajectories: True
  histograms: True
  grid: True
parameter_combinations: taux${params.taux}_tauu${params.tauu}_dt${params.dt}_sigma${params.sigma}_${params.grid.name}
hydra:
  verbose: False
  job:
    name: ${params.env_name}_${parameter_combinations}
    chdir: True
  run:
    dir: outputs/${params.env_name}/${parameter_combinations}/${now:%Y-%m-%d_%H-%M-%S}
