defaults:
  - params: narrow_corridor
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_
read:
  preprocessed_trajectories: False
  piecewise_potential: False
  simulated_trajectories: False
save:
  preprocessed_trajectories: False
  piecewise_potential: False
  simulated_trajectories: False
filename:
  preprocessed_trajectories: preprocessed_trajectories_with_tau${params.model.taux}.csv
  piecewise_potential: piecewise_potential_with_${params.grid.name}.pickle
  simulated_trajectories: simulated_trajectories_with_sigma${params.model.sigma}.csv
plot:
  preprocessed_trajectories: True
  simulated_trajectories: True
  histograms: True
  grid: True
  potential_at_selection: True
plot_style: conf/science.mplstyle
root_dir: ${get_root_dir:}
trajectory_data_dir: data/trajectories
parameter_combinations: sigma${params.model.sigma}_${params.grid.name}
hydra:
  verbose: False
  job:
    name: ${params.env_name}_${parameter_combinations}
    chdir: True
  run:
    dir: outputs/${params.env_name}_tauu${params.model.tauu}/${params.grid.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: multirun/${params.env_name}/${params.grid.name}
    subdir: job${hydra.job.num}-sigma${params.model.sigma}-tauu${params.model.tauu}-${params.grid.name}-${now:%Y-%m-%d_%H-%M-%S}
