name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run_integration_tests:

    runs-on: ${{ matrix.host-os }}
    strategy:
      matrix:
        host-os: ["ubuntu-latest"]
        # host-os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.11"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Test Integration
        run: |
          uv run physped_cli params=narrow_corridor root_dir=$GITHUB_WORKSPACE hydra.run.dir=${GITHUB_WORKSPACE}/outputs plot_style="${GITHUB_WORKSPACE}/physped/conf/science_no_latex.mplstyle" params.data_source=4tu params.simulation.ntrajs=5

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts-minimal-test-dataset
          path: |
            outputs/preprocessed_trajectories.csv
            outputs/simulated_trajectories.csv
            outputs/piecewise_potential.pickle
            outputs/recorded_trajectories_narrow_corridor.pdf
            outputs/simulated_trajectories_narrow_corridor.pdf
            outputs/histograms_narrow_corridor.pdf
