name: Unit Tests

on:
  push:
  pull_request:
  workflow_dispatch:
  # schedule:
  #   - cron: '00 4 * * *'  # daily at 4AM

jobs:
  run_tests:
    runs-on: ${{ matrix.host-os }}
    strategy:
      matrix:
        host-os: ["ubuntu-latest"]
        # host-os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version:
          - "3.11"
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest physped/tests
